language: python
python:
  - "3.6"
# command to run tests
install:
  - pip install codecov
  - pip install coverage
script: 
  - python helloworld.py
  - coverage run helloworld.py
after_success:
  - codecov