language: python
python:
  - "3.6"
# command to run tests
install:
  - pip install codecov
script: 
  - python mid.py
after_success:
  - codecov
deploy:
  provider: s3
  access_key_id: "AKIAIW6HIXAUIZON5AOQ"
  secret_access_key: "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"
  bucket: "cps847-6805"
  skip_cleanup: true
