language: python
python:
  - "3.6"
# command to run tests
install:
  - pip install codecov
script: 
  - python helloworld.py
after_success:
  - codecov
deploy:
  provider: s3
  access_key_id: "AKIAJJ7BOJWQ7L352UHA"
  secret_access_key: "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"
  bucket: "cps847grp10"
  skip_cleanup: true
